# Generated by Django 5.2.15 on 2026-07-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system_admin', 'System Admin'), ('national_manager', 'National Project Manager'), ('union_focal', 'Trade Union Focal Person'), ('data_collector', 'Data Collector'), ('read_only', 'Read-Only')], max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User category / role setting',
                'verbose_name_plural': 'User categories / role settings',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
    ]
