# Generated by Django 4.2.27 on 2026-06-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('role_or_group', models.CharField(blank=True, max_length=160)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('comment', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('planned', 'Planned'), ('closed', 'Closed')], default='new', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
