# Generated by Django 4.2.27 on 2026-06-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('activity_type', models.CharField(choices=[('training', 'Training'), ('workshop', 'Workshop'), ('audit', 'Accessibility audit'), ('employer_engagement', 'Employer engagement'), ('advocacy', 'Advocacy intervention'), ('organising', 'Organising activity')], max_length=40)),
                ('partner', models.CharField(blank=True, max_length=160)),
                ('province', models.CharField(choices=[('Central', 'Central'), ('Copperbelt', 'Copperbelt'), ('Eastern', 'Eastern'), ('Luapula', 'Luapula'), ('Lusaka', 'Lusaka'), ('Muchinga', 'Muchinga'), ('Northern', 'Northern'), ('North-Western', 'North-Western'), ('Southern', 'Southern'), ('Western', 'Western')], max_length=40)),
                ('district', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('participants_total', models.PositiveIntegerField(default=0)),
                ('participants_with_disabilities', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Project activities',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('participant', 'Participant'), ('facilitator', 'Facilitator'), ('observer', 'Observer')], default='participant', max_length=40)),
                ('attended', models.BooleanField(default=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='monitoring.projectactivity')),
            ],
            options={
                'ordering': ['activity', 'worker__last_name'],
            },
        ),
    ]
