# Generated by Django 4.2.27 on 2026-06-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingattendance',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_attendance', to='workers.worker'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingattendance',
            unique_together={('activity', 'worker')},
        ),
    ]
