# Generated by Django 5.2.15 on 2026-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectactivity',
            name='district',
            field=models.CharField(choices=[('Central', [('Chibombo', 'Chibombo'), ('Chisamba', 'Chisamba'), ('Chitambo', 'Chitambo'), ('Itezhi-Tezhi', 'Itezhi-Tezhi'), ('Kabwe', 'Kabwe'), ('Kapiri Mposhi', 'Kapiri Mposhi'), ('Luano', 'Luano'), ('Mkushi', 'Mkushi'), ('Mumbwa', 'Mumbwa'), ('Ngabwe', 'Ngabwe'), ('Serenje', 'Serenje'), ('Shibuyunji', 'Shibuyunji')]), ('Copperbelt', [('Chililabombwe', 'Chililabombwe'), ('Chingola', 'Chingola'), ('Kalulushi', 'Kalulushi'), ('Kitwe', 'Kitwe'), ('Luanshya', 'Luanshya'), ('Lufwanyama', 'Lufwanyama'), ('Masaiti', 'Masaiti'), ('Mpongwe', 'Mpongwe'), ('Mufulira', 'Mufulira'), ('Ndola', 'Ndola')]), ('Eastern', [('Chadiza', 'Chadiza'), ('Chasefu', 'Chasefu'), ('Chipangali', 'Chipangali'), ('Chipata', 'Chipata'), ('Kasenengwa', 'Kasenengwa'), ('Katete', 'Katete'), ('Lumezi', 'Lumezi'), ('Lundazi', 'Lundazi'), ('Lusangazi', 'Lusangazi'), ('Mambwe', 'Mambwe'), ('Nyimba', 'Nyimba'), ('Petauke', 'Petauke'), ('Sinda', 'Sinda'), ('Vubwi', 'Vubwi')]), ('Luapula', [('Chembe', 'Chembe'), ('Chiengi', 'Chiengi'), ('Chifunabuli', 'Chifunabuli'), ('Chipili', 'Chipili'), ('Kawambwa', 'Kawambwa'), ('Lunga', 'Lunga'), ('Mansa', 'Mansa'), ('Milenge', 'Milenge'), ('Mwansabombwe', 'Mwansabombwe'), ('Mwense', 'Mwense'), ('Nchelenge', 'Nchelenge'), ('Samfya', 'Samfya')]), ('Lusaka', [('Chilanga', 'Chilanga'), ('Chirundu', 'Chirundu'), ('Chongwe', 'Chongwe'), ('Kafue', 'Kafue'), ('Luangwa', 'Luangwa'), ('Lusaka', 'Lusaka'), ('Rufunsa', 'Rufunsa')]), ('Muchinga', [('Chama', 'Chama'), ('Chinsali', 'Chinsali'), ('Isoka', 'Isoka'), ('Kanchibiya', 'Kanchibiya'), ('Lavushimanda', 'Lavushimanda'), ('Mafinga', 'Mafinga'), ('Mpika', 'Mpika'), ('Nakonde', 'Nakonde'), ("Shiwang'andu", "Shiwang'andu")]), ('Northern', [('Chilubi', 'Chilubi'), ('Kaputa', 'Kaputa'), ('Kasama', 'Kasama'), ('Lunte', 'Lunte'), ('Lupososhi', 'Lupososhi'), ('Luwingu', 'Luwingu'), ('Mbala', 'Mbala'), ('Mporokoso', 'Mporokoso'), ('Mpulungu', 'Mpulungu'), ('Mungwi', 'Mungwi'), ('Nsama', 'Nsama'), ('Senga Hill', 'Senga Hill')]), ('North-Western', [('Chavuma', 'Chavuma'), ('Ikelenge', 'Ikelenge'), ('Kabompo', 'Kabompo'), ('Kalumbila', 'Kalumbila'), ('Kasempa', 'Kasempa'), ('Manyinga', 'Manyinga'), ('Mufumbwe', 'Mufumbwe'), ('Mushindamo', 'Mushindamo'), ('Mwinilunga', 'Mwinilunga'), ('Solwezi', 'Solwezi'), ('Zambezi', 'Zambezi')]), ('Southern', [('Chikankata', 'Chikankata'), ('Choma', 'Choma'), ('Gwembe', 'Gwembe'), ('Kalomo', 'Kalomo'), ('Kazungula', 'Kazungula'), ('Livingstone', 'Livingstone'), ('Mazabuka', 'Mazabuka'), ('Monze', 'Monze'), ('Namwala', 'Namwala'), ('Pemba', 'Pemba'), ('Siavonga', 'Siavonga'), ('Sinazongwe', 'Sinazongwe'), ('Zimba', 'Zimba')]), ('Western', [('Kalabo', 'Kalabo'), ('Kaoma', 'Kaoma'), ('Limulunga', 'Limulunga'), ('Luampa', 'Luampa'), ('Lukulu', 'Lukulu'), ('Mitete', 'Mitete'), ('Mongu', 'Mongu'), ('Mulobezi', 'Mulobezi'), ('Mwandi', 'Mwandi'), ('Nalolo', 'Nalolo'), ('Nkeyema', 'Nkeyema'), ('Senanga', 'Senanga'), ('Sesheke', 'Sesheke'), ('Shangombo', 'Shangombo'), ('Sikongo', 'Sikongo'), ('Sioma', 'Sioma')])], max_length=80),
        ),
    ]
