from django.core.exceptions import ValidationError
from django.test import TestCase
from django.urls import reverse

from .models import User
from .totp import generate_secret, generate_totp, provisioning_uri, verify_totp


class UserModelTests(TestCase):
    def test_is_system_admin_true_for_superuser_regardless_of_role(self):
        user = User.objects.create_user(username="admin1", password="pw", is_superuser=True, role=User.ROLE_READ_ONLY)
        self.assertTrue(user.is_system_admin)

    def test_can_edit_records_false_for_read_only(self):
        user = User.objects.create_user(username="ro", password="pw", role=User.ROLE_READ_ONLY)
        self.assertFalse(user.can_edit_records)

    def test_can_edit_records_true_for_data_collector(self):
        user = User.objects.create_user(username="collector", password="pw", role=User.ROLE_DATA_COLLECTOR)
        self.assertTrue(user.can_edit_records)

    def test_totp_secret_autogenerated_when_enabled_flag_set_directly(self):
        # Exercises the model-level safety net in User.save(): even if something
        # sets totp_enabled=True without going through self-enrollment, the user
        # still ends up with *some* secret rather than an unusable blank one.
        user = User.objects.create_user(username="direct2fa", password="pw")
        user.totp_enabled = True
        user.save()
        self.assertTrue(user.totp_secret)


class TOTPTests(TestCase):
    def test_generate_and_verify_round_trip(self):
        secret = generate_secret()
        code = generate_totp(secret)
        self.assertTrue(verify_totp(secret, code))

    def test_verify_rejects_wrong_code(self):
        secret = generate_secret()
        correct_code = generate_totp(secret)
        wrong_code = "000000" if correct_code != "000000" else "111111"
        self.assertFalse(verify_totp(secret, wrong_code))

    def test_verify_rejects_non_numeric_code(self):
        secret = generate_secret()
        self.assertFalse(verify_totp(secret, "abcdef"))

    def test_provisioning_uri_includes_issuer_and_secret(self):
        uri = provisioning_uri("ABCDEF123456", "alice", issuer="DLDMS")
        self.assertIn("secret=ABCDEF123456", uri)
        self.assertIn("issuer=DLDMS", uri)
        self.assertTrue(uri.startswith("otpauth://totp/"))


class LoginAndTwoFactorFlowTests(TestCase):
    def setUp(self):
        self.password = "S0meStrongPW!"
        self.user_no_2fa = User.objects.create_user(username="plain", password=self.password)
        self.secret = generate_secret()
        self.user_with_2fa = User.objects.create_user(
            username="withotp", password=self.password, totp_enabled=True, totp_secret=self.secret
        )

    def test_login_without_2fa_logs_in_directly(self):
        response = self.client.post(
            reverse("users:login"), {"username": "plain", "password": self.password}
        )
        self.assertRedirects(response, reverse("dashboards:home"))

    def test_login_with_2fa_redirects_to_verify_otp(self):
        response = self.client.post(
            reverse("users:login"), {"username": "withotp", "password": self.password}
        )
        self.assertRedirects(response, reverse("users:verify-otp"))

    def test_verify_otp_with_correct_code_completes_login(self):
        self.client.post(reverse("users:login"), {"username": "withotp", "password": self.password})
        code = generate_totp(self.secret)
        response = self.client.post(reverse("users:verify-otp"), {"code": code})
        self.assertRedirects(response, reverse("dashboards:home"))

    def test_verify_otp_with_wrong_code_does_not_log_in(self):
        self.client.post(reverse("users:login"), {"username": "withotp", "password": self.password})
        wrong_code = "000000" if generate_totp(self.secret) != "000000" else "111111"
        response = self.client.post(reverse("users:verify-otp"), {"code": wrong_code})
        self.assertEqual(response.status_code, 400)

    def test_totp_setup_requires_login(self):
        response = self.client.get(reverse("users:totp-setup"))
        self.assertNotEqual(response.status_code, 200)

    def test_totp_setup_enroll_and_confirm(self):
        self.client.login(username="plain", password=self.password)
        get_response = self.client.get(reverse("users:totp-setup"))
        self.assertEqual(get_response.status_code, 200)
        pending_secret = self.client.session["totp_pending_secret"]

        code = generate_totp(pending_secret)
        post_response = self.client.post(reverse("users:totp-setup"), {"code": code})
        self.assertRedirects(post_response, reverse("users:totp-setup"))

        self.user_no_2fa.refresh_from_db()
        self.assertTrue(self.user_no_2fa.totp_enabled)
        self.assertEqual(self.user_no_2fa.totp_secret, pending_secret)

    def test_totp_disable_requires_correct_password(self):
        self.client.login(username="withotp", password=self.password)
        response = self.client.post(reverse("users:totp-disable"), {"password": "wrong-password"})
        self.assertRedirects(response, reverse("users:totp-setup"))
        self.user_with_2fa.refresh_from_db()
        self.assertTrue(self.user_with_2fa.totp_enabled)

    def test_totp_disable_with_correct_password_turns_off_2fa(self):
        self.client.login(username="withotp", password=self.password)
        response = self.client.post(reverse("users:totp-disable"), {"password": self.password})
        self.assertRedirects(response, reverse("users:totp-setup"))
        self.user_with_2fa.refresh_from_db()
        self.assertFalse(self.user_with_2fa.totp_enabled)
        self.assertEqual(self.user_with_2fa.totp_secret, "")

    def test_admin_can_reset_but_not_enable_2fa_for_another_user(self):
        admin = User.objects.create_user(
            username="sysadmin", password=self.password, role=User.ROLE_SYSTEM_ADMIN
        )
        self.client.login(username="sysadmin", password=self.password)
        response = self.client.post(reverse("users:settings-totp-reset", args=[self.user_with_2fa.pk]))
        self.assertEqual(response.status_code, 302)
        self.user_with_2fa.refresh_from_db()
        self.assertFalse(self.user_with_2fa.totp_enabled)

        # The admin form must never expose a way to flip totp_enabled on directly —
        # that would lock the user out with a secret they've never seen/scanned.
        from .forms import UserManagementForm

        self.assertNotIn("totp_enabled", UserManagementForm().fields)
