# Generated by Django 4.2.27 on 2026-06-30 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import workers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_id', models.CharField(default=workers.models.generate_worker_id, editable=False, max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('other_names', models.CharField(blank=True, max_length=120)),
                ('national_id', models.CharField(blank=True, max_length=80)),
                ('nationality', models.CharField(default='Zambian', max_length=80)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], max_length=32)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('province', models.CharField(choices=[('Central', 'Central'), ('Copperbelt', 'Copperbelt'), ('Eastern', 'Eastern'), ('Luapula', 'Luapula'), ('Lusaka', 'Lusaka'), ('Muchinga', 'Muchinga'), ('Northern', 'Northern'), ('North-Western', 'North-Western'), ('Southern', 'Southern'), ('Western', 'Western')], max_length=40)),
                ('district', models.CharField(max_length=80)),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture'), ('mining', 'Mining'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('transport', 'Transport'), ('education', 'Education'), ('health', 'Health'), ('hospitality', 'Hospitality'), ('public_service', 'Public service'), ('commerce', 'Commerce'), ('domestic_work', 'Domestic work'), ('other', 'Other')], max_length=60)),
                ('occupation', models.CharField(blank=True, max_length=140)),
                ('employment_status', models.CharField(choices=[('formal', 'Formal employment'), ('informal', 'Informal employment'), ('self_employed', 'Self-employed'), ('apprenticeship', 'Apprenticeship'), ('unemployed', 'Unemployed'), ('retired', 'Retired')], max_length=40)),
                ('union_membership_status', models.CharField(choices=[('member', 'Union member'), ('not_member', 'Not a union member'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('union_name', models.CharField(blank=True, max_length=160)),
                ('leadership_participation', models.BooleanField(default=False)),
                ('committee_participation', models.BooleanField(default=False)),
                ('organising_activities', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo', models.ImageField(blank=True, upload_to=workers.models.worker_photo_path)),
                ('consent_to_store_data', models.BooleanField(default=True)),
                ('data_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_name', models.CharField(max_length=180)),
                ('workplace_name', models.CharField(blank=True, max_length=180)),
                ('province', models.CharField(choices=[('Central', 'Central'), ('Copperbelt', 'Copperbelt'), ('Eastern', 'Eastern'), ('Luapula', 'Luapula'), ('Lusaka', 'Lusaka'), ('Muchinga', 'Muchinga'), ('Northern', 'Northern'), ('North-Western', 'North-Western'), ('Southern', 'Southern'), ('Western', 'Western')], max_length=40)),
                ('district', models.CharField(max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(choices=[('agriculture', 'Agriculture'), ('mining', 'Mining'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('transport', 'Transport'), ('education', 'Education'), ('health', 'Health'), ('hospitality', 'Hospitality'), ('public_service', 'Public service'), ('commerce', 'Commerce'), ('domestic_work', 'Domestic work'), ('other', 'Other')], max_length=60)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('accessibility_status', models.CharField(choices=[('accessible', 'Accessible'), ('partially_accessible', 'Partially accessible'), ('not_accessible', 'Not accessible'), ('not_assessed', 'Not yet assessed')], default='not_assessed', max_length=40)),
                ('accommodations_available', models.TextField(blank=True)),
                ('union_presence', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['employer_name', 'district'],
            },
        ),
        migrations.CreateModel(
            name='WorkerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('document_type', models.CharField(choices=[('photo', 'Photo'), ('audit', 'Audit evidence'), ('medical', 'Medical or assessment document'), ('consent', 'Consent document'), ('other', 'Other')], default='other', max_length=40)),
                ('file', models.FileField(upload_to=workers.models.worker_document_path)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='workers.workplace'),
        ),
        migrations.CreateModel(
            name='LabourRightsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grievance_reported', models.BooleanField(default=False)),
                ('grievance_summary', models.TextField(blank=True)),
                ('case_status', models.CharField(choices=[('none', 'No active case'), ('open', 'Open'), ('monitoring', 'Monitoring'), ('referred', 'Referred'), ('resolved', 'Resolved')], default='none', max_length=32)),
                ('legal_support_provided', models.BooleanField(default=False)),
                ('collective_bargaining_coverage', models.BooleanField(default=False)),
                ('social_protection_coverage', models.BooleanField(default=False)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='labour_rights', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Labour rights record',
                'verbose_name_plural': 'Labour rights records',
            },
        ),
        migrations.CreateModel(
            name='DisabilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disability_type', models.CharField(choices=[('physical', 'Physical impairment'), ('visual', 'Visual impairment'), ('hearing', 'Hearing impairment'), ('intellectual', 'Intellectual disability'), ('psychosocial', 'Psychosocial disability'), ('albinism', 'Albinism'), ('multiple', 'Multiple disabilities'), ('other', 'Other')], max_length=40)),
                ('other_disability_type', models.CharField(blank=True, max_length=160)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('profound', 'Profound')], max_length=40)),
                ('assistive_devices', models.TextField(blank=True)),
                ('accommodation_requirements', models.TextField(blank=True)),
                ('accessibility_challenges', models.TextField(blank=True)),
                ('functional_limitations', models.TextField(blank=True)),
                ('wg_seeing', models.PositiveSmallIntegerField(choices=[(0, 'No difficulty'), (1, 'Some difficulty'), (2, 'A lot of difficulty'), (3, 'Cannot do at all')], default=0)),
                ('wg_hearing', models.PositiveSmallIntegerField(choices=[(0, 'No difficulty'), (1, 'Some difficulty'), (2, 'A lot of difficulty'), (3, 'Cannot do at all')], default=0)),
                ('wg_walking', models.PositiveSmallIntegerField(choices=[(0, 'No difficulty'), (1, 'Some difficulty'), (2, 'A lot of difficulty'), (3, 'Cannot do at all')], default=0)),
                ('wg_remembering', models.PositiveSmallIntegerField(choices=[(0, 'No difficulty'), (1, 'Some difficulty'), (2, 'A lot of difficulty'), (3, 'Cannot do at all')], default=0)),
                ('wg_self_care', models.PositiveSmallIntegerField(choices=[(0, 'No difficulty'), (1, 'Some difficulty'), (2, 'A lot of difficulty'), (3, 'Cannot do at all')], default=0)),
                ('wg_communicating', models.PositiveSmallIntegerField(choices=[(0, 'No difficulty'), (1, 'Some difficulty'), (2, 'A lot of difficulty'), (3, 'Cannot do at all')], default=0)),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disability_profile', to='workers.worker')),
            ],
            options={
                'ordering': ['worker__last_name', 'worker__first_name'],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('auditor_name', models.CharField(max_length=160)),
                ('entrance_score', models.PositiveSmallIntegerField(default=0)),
                ('restroom_score', models.PositiveSmallIntegerField(default=0)),
                ('workstation_score', models.PositiveSmallIntegerField(default=0)),
                ('transport_score', models.PositiveSmallIntegerField(default=0)),
                ('findings', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('evidence_upload', models.FileField(blank=True, upload_to=workers.models.audit_document_path)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='workers.workplace')),
            ],
            options={
                'ordering': ['-audit_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['unique_id'], name='workers_wor_unique__054555_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['province', 'district'], name='workers_wor_provinc_9d994c_idx'),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['union_name'], name='workers_wor_union_n_de3d58_idx'),
        ),
    ]
