# Generated by Django 5.2.15 on 2026-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_alter_worker_district_alter_workplace_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, unique=True)),
                ('sector', models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('mining', 'Mining'), ('manufacturing', 'Manufacturing'), ('construction', 'Construction'), ('transport', 'Transport'), ('education', 'Education'), ('health', 'Health'), ('hospitality', 'Hospitality'), ('public_service', 'Public service'), ('commerce', 'Commerce'), ('domestic_work', 'Domestic work'), ('other', 'Other')], max_length=60)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Occupation setting',
                'verbose_name_plural': 'Occupation settings',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
