# Generated by Django 5.2.15 on 2026-07-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_seed_occupation_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trade union setting',
                'verbose_name_plural': 'Trade union settings',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
