# Generated by Django 5.2.15 on 2026-08-31 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_workplace_accommodations_available_boolean'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='capture_mode',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline queued')], default='online', max_length=16),
        ),
        migrations.AddField(
            model_name='worker',
            name='capture_source',
            field=models.CharField(choices=[('web', 'Web portal'), ('mobile', 'Mobile app')], default='web', max_length=16),
        ),
        migrations.AddField(
            model_name='worker',
            name='captured_at_device',
            field=models.DateTimeField(blank=True, help_text='Original device timestamp for records first captured offline.', null=True),
        ),
        migrations.AddIndex(
            model_name='worker',
            index=models.Index(fields=['capture_source', 'capture_mode'], name='workers_wor_capture_51b30b_idx'),
        ),
    ]
