from django.core.exceptions import ValidationError
from django.test import TestCase
from django.urls import reverse

from users.models import User
from users.permissions import filter_workers_for_user, filter_workplaces_for_user

from .models import DisabilityProfile, Workplace, Worker


def make_workplace(**overrides):
    defaults = dict(
        employer_name="Copperbelt Mine Services",
        province="Central",
        district="Chibombo",
        sector="agriculture",
    )
    defaults.update(overrides)
    return Workplace.objects.create(**defaults)


def make_worker(**overrides):
    defaults = dict(
        first_name="Chanda",
        last_name="Mwansa",
        gender="female",
        province="Central",
        district="Chibombo",
        sector="agriculture",
        employment_status="formal",
    )
    defaults.update(overrides)
    return Worker.objects.create(**defaults)


class WorkplaceModelTests(TestCase):
    def test_district_must_belong_to_province(self):
        workplace = Workplace(
            employer_name="Test employer",
            province="Central",
            district="Kitwe",  # Kitwe is on the Copperbelt, not Central
            sector="agriculture",
        )
        with self.assertRaises(ValidationError):
            workplace.full_clean()

    def test_valid_province_district_pair_passes(self):
        workplace = Workplace(
            employer_name="Test employer",
            province="Central",
            district="Chibombo",
            sector="agriculture",
        )
        workplace.full_clean()  # should not raise


class WorkerModelTests(TestCase):
    def test_unique_id_is_autogenerated(self):
        worker = make_worker()
        self.assertTrue(worker.unique_id.startswith("DLDMS-"))

    def test_disability_profile_links_one_to_one(self):
        worker = make_worker()
        profile = DisabilityProfile.objects.create(worker=worker, disability_type="physical", severity="mild")
        self.assertEqual(worker.disability_profile, profile)


class RBACFilteringTests(TestCase):
    """Covers users.permissions.filter_workers_for_user / filter_workplaces_for_user,
    including the fail-closed fix for union-scoped roles with no assigned_union."""

    def setUp(self):
        self.worker_muz = make_worker(union_name="MUZ")
        self.worker_other = make_worker(first_name="Bwalya", union_name="BETUZ")
        self.admin = User.objects.create_user(username="admin_t", password="pw", role=User.ROLE_SYSTEM_ADMIN)
        self.national_manager = User.objects.create_user(username="nm_t", password="pw", role=User.ROLE_NATIONAL_MANAGER)
        self.focal_with_union = User.objects.create_user(
            username="focal_t", password="pw", role=User.ROLE_UNION_FOCAL, assigned_union="MUZ"
        )
        self.focal_without_union = User.objects.create_user(
            username="focal_unset_t", password="pw", role=User.ROLE_UNION_FOCAL
        )

    def test_admin_sees_all_workers(self):
        result = filter_workers_for_user(Worker.objects.all(), self.admin)
        self.assertEqual(result.count(), 2)

    def test_national_manager_sees_all_workers(self):
        result = filter_workers_for_user(Worker.objects.all(), self.national_manager)
        self.assertEqual(result.count(), 2)

    def test_union_focal_sees_only_their_union(self):
        result = filter_workers_for_user(Worker.objects.all(), self.focal_with_union)
        self.assertEqual(list(result), [self.worker_muz])

    def test_union_focal_with_no_assigned_union_sees_nothing(self):
        # Regression test for the fail-open bug: an unconfigured union-scoped
        # account must not fall through to seeing every union's workers.
        result = filter_workers_for_user(Worker.objects.all(), self.focal_without_union)
        self.assertEqual(result.count(), 0)

    def test_anonymous_sees_nothing(self):
        from django.contrib.auth.models import AnonymousUser

        result = filter_workers_for_user(Worker.objects.all(), AnonymousUser())
        self.assertEqual(result.count(), 0)

    def test_workplace_filtering_matches_worker_filtering(self):
        workplace_muz = make_workplace(employer_name="MUZ employer")
        self.worker_muz.workplace = workplace_muz
        self.worker_muz.save()

        result = filter_workplaces_for_user(Workplace.objects.all(), self.focal_with_union)
        self.assertEqual(list(result), [workplace_muz])

        result_unset = filter_workplaces_for_user(Workplace.objects.all(), self.focal_without_union)
        self.assertEqual(result_unset.count(), 0)


class WorkerListViewTests(TestCase):
    def setUp(self):
        make_worker()
        self.admin = User.objects.create_user(username="admin_v", password="pw", role=User.ROLE_SYSTEM_ADMIN)

    def test_worker_list_requires_login(self):
        response = self.client.get(reverse("workers:list"))
        self.assertNotEqual(response.status_code, 200)

    def test_worker_list_loads_for_admin(self):
        self.client.login(username="admin_v", password="pw")
        response = self.client.get(reverse("workers:list"))
        self.assertEqual(response.status_code, 200)
